### ISSUE TITLE
NoClassDefFoundError: com/vdurmont/emoji/EmojiParser

### ISSUE THREAD

**Issue by Vap0r1ze** [Vap0r1ze/EmojiChat#3]
RadBuilder/EmojiChat#30

**Comment by mibby** [comment]
Changed again so need to recompile against latest DiscordSRV / Staff Chat.

```
[01:38:33] [Server thread/ERROR]: Could not pass event PlayerStaffChatMessageEvent to EmojiChat v2.0.2
[01:38:33] [Server thread/ERROR]: Suspected Plugins: 
[01:38:33] [Server thread/ERROR]: 	EmojiChat{enabled,ver=2.0.2,path=plugins/EmojiChat.jar}
[01:38:33] [Server thread/ERROR]: 	DiscordSRV-Staff-Chat{enabled,ver=1.3.4,path=plugins/DiscordSRV-Staff-Chat-1.3.4.jar}
[01:38:33] [Server thread/ERROR]: Exception details below: 
java.lang.NoSuchMethodError: 'org.bukkit.entity.Player com.rezzedup.discordsrv.staffchat.events.PlayerStaffChatMessageEvent.getAuthor()'
	at io.github.radbuilder.emojichat.hooks.DiscordSrvStaffChatHook.onMinecraftStaffChat(DiscordSrvStaffChatHook.java:57) ~[?:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor980.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:76) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:611) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at com.rezzedup.discordsrv.staffchat.util.Events.call(Events.java:12) ~[?:?]
	at com.rezzedup.discordsrv.staffchat.StaffChatPlugin.submitMessageFromInGame(StaffChatPlugin.java:199) ~[?:?]
	at com.rezzedup.discordsrv.staffchat.StaffChatPlugin.onCommand(StaffChatPlugin.java:299) ~[?:?]
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:810) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2298) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:2113) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:2066) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:50) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:8) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:55) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1336) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1329) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:1305) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1145) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Yatopia-ver/1.16.5-"d99cf54"]
	at java.lang.Thread.run(Thread.java:834) [?:?]
```
